spring:
  application:
    name: Planer
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./db/PlanerDB
    username: WebUser
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: h2
    hibernate:
      ddl-auto: update

